exp_name: 'hpc_4xGPU'

system:
  gpus: 4
  workers: 1
  batch_size: 32
  path: '/work1/wshah/xzhang/challenge'
  results_path: '/work1/wshah/xzhang/challenge/src/results/'

data:
  root: '/work1/wshah/xzhang/data'

model:
  backbone: 'vit'
  size: 'base'
  image_size: 384
  epochs: 10



