exp_name: 'hpc_4xGPU'

system:
  gpus: 1
  workers: 2
  batch_size: 32
  path: '/work1/wshah/xzhang/challenge'
  results_path: '/work1/wshah/xzhang/challenge/src/results/'
  amd_cluster: True
  scheduler: 'cos'

data:
  root: '/work1/wshah/xzhang/data/university-1652/University-1652'

model:
  shared_extractor: False
  backbone: 'convnext'
  size: 'base'
  image_size: 224
  epochs: 20
  lr: 1e-4
  miner: False



